name: image_picker_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web:
    path: ../
  image_picker_platform_interface:
    git:
      url: https://github.com/Construction-Connectivity-LLC/image_picker.git
      ref: main
      path: image_picker_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  js: ^0.6.3
